# **Exercise 1**

Create a Python class which contains two methods. The first method takes a string as arguments and changes all a characters inside the string to X. The second method takes a number and returns the number's fractinal part. (1p)



In [ ]:
class Exercise1:

  def first_method(String):
    new_string = String.replace('a', 'X')
    return new_string


  def second_method(Number):
   new_number = float(Number) - int(Number)
   return new_number



print(Exercise1.first_method(input("please enter string")))
print(Exercise1.second_method(float(input("Please enter Number"))))


please enter stringsadsad
sXdsXd
Please enter Number1
0.0


### Exercise 2
Define the below matrices using Numpy and determine the followings (1p):

1. Their dot product
2. Their elementwise product
3. Their sum
4. The sum of the A matrix elements
5. The first (index 0) row of the B matrix
6. The second (index 1) column of the B matrix
7. Create a C matrix from A without A's first column   

In all cases, the result need to be printed out!

A = $\begin{bmatrix}
5 & 6 & 8\\
2 & 3 & 2
\end{bmatrix}$ B = $\begin{bmatrix}
1 & 3 & 1\\
2 & 3 & 3
\end{bmatrix}$

In [ ]:
import numpy as np
A = np.array([[5, 6, 8],[2, 3, 2]])
B = np.array([[1, 3, 1],[2, 3, 3]])

print(np.dot(A,B.T)) #We need to transpose B because it is 2x3
print("-------------------")
print(A*B)
print("-------------------")
print(A+B)
print("-------------------")
print(A.sum())
print("-------------------")
print(B[0,:])
print("-------------------")
print(B[:,1])
print("-------------------")
C = A[0:, 1:]
print(C)
print("-------------------")


[[31 52]
 [13 19]]
-------------------
[[ 5 18  8]
 [ 4  9  6]]
-------------------
[[6 9 9]
 [4 6 5]]
-------------------
26
-------------------
[1 3 1]
-------------------
[3 3]
-------------------
[[6 8]
 [3 2]]
-------------------


### Exercise 3
Suppose that we have a silly robot which can communicate with Morse codes and we received the following message. <br>
.-- . .-.. -.-. --- -- . / .. -. / - .... . / -- .-.. / -.-. --- ..- .-. ... .  

Write a function to decode the message into human readable format. (1p)

In [ ]:
def Exercise3(code):
  morse = {
    ".-": "A", "-...": "B", "-.-.": "C", "-..": "D", ".": "E",
        "..-.": "F", "--.": "G", "....": "H", "..": "I", ".---": "J",
        "-.-": "K", ".-..": "L", "--": "M", "-.": "N", "---": "O",
        ".--.": "P", "--.-": "Q", ".-.": "R", "...": "S", "-": "T",
        "..-": "U", "...-": "V", ".--": "W", "-..-": "X",
        "-.--": "Y", "--..": "Z",
        "/": " "}
  words = code.split() #because there's separation with space character
                       #in each morse letter

  result = "" #using as a bag to collect and Concatenation the words together

  for arrow in words:
        result += morse[arrow]

  return result
print(Exercise3(".-- . .-.. -.-. --- -- . / .. -. / - .... . / -- .-.. / -.-. --- ..- .-. ... ."))

WELCOME IN THE ML COURSE
